import turtle
# a=turtle.Pen()
# a.shape('turtle')
# a.color('gray')
# a.begin_fill()
# a.circle(130)
# a.end_fill()

# turtle.exitonclick()
# a=turtle.Pen()
# a.color('gray')
# a.shape('triangle')
# b=turtle.Pen()
# b.color('pink')
# b.shape('circle')
# a.forward(200)
# b.forward(100)
# b.left(90)
# b.forward(70)
# b.right(90)
# b.forward(100) 
# turtle.exitonclick()
a=turtle.Pen()
a.circle(100)
a.left(72)
a.circle(100) 
a. color('red')